// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'centered': string;
  'gap': string;
  'root': string;
  'scrolled': string;
}
export const cssExports: CssExports;
export default cssExports;
