// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'menu': string;
  'root': string;
  'user': string;
  'userName': string;
}
export const cssExports: CssExports;
export default cssExports;
