// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'breath': string;
  'inner': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
