// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bg': string;
  'breath': string;
  'fadeOut': string;
  'hueCycle': string;
  'inner': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
