// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'breathing': string;
  'contacts': string;
  'iconBtn': string;
  'root': string;
  'thinkingOutline': string;
  'thinkingOutlineContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
