// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clear': string;
  'clearPadding': string;
  'disabled': string;
  'exact': string;
  'external': string;
  'externalIcon': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
