// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer': string;
  'form': string;
  'gap': string;
  'header': string;
  'link': string;
  'root': string;
  'submitButtons': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
