// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'scroll': string;
  'scrollInner': string;
  'chevron': string;
  'version': string;
}
export const cssExports: CssExports;
export default cssExports;
