// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'control': string;
  'error': string;
  'input': string;
  'label': string;
  'progress': string;
  'root': string;
  'size-l': string;
  'size-m': string;
  'size-s': string;
  'success': string;
}
export const cssExports: CssExports;
export default cssExports;
