// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close': string;
  'content': string;
  'icon': string;
  'item': string;
  'itemInner': string;
  'item_type_error': string;
  'item_type_info': string;
  'item_type_success': string;
  'item_visible': string;
  'root': string;
  'text': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
