// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer': string;
  'gap': string;
  'langSwitcherEmpty': string;
  'root': string;
  'slug': string;
  'slugWrap': string;
  'versionButton': string;
}
export const cssExports: CssExports;
export default cssExports;
