// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'date': string;
  'footer': string;
  'root': string;
  'scroll': string;
  'scrollInner': string;
}
export const cssExports: CssExports;
export default cssExports;
