// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item': string;
  'list': string;
  'root': string;
  'scroll': string;
  'scrollInner': string;
}
export const cssExports: CssExports;
export default cssExports;
