// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clickable': string;
  'highlighted': string;
  'horizontal': string;
  'item': string;
  'padded': string;
  'paddedX': string;
  'right': string;
  'root': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
