// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app-title': string;
  'gap': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
